# Config file for automatic testing at travis-ci.org
language: python
jobs:
  include:
    - name: "Python 3.8 on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.8
      env: python_version=3.8

    - name: "Python 3.9 on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.9
      env: python_version=3.9

    - name: "Python 3.10 on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.10
      env: python_version=3.10

    - name: "Python 3.11 on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.11
      env: python_version=3.11

    - name: "Python 3.12 on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.12
      env: python_version=3.12

    -   name: "Python 3.13 on Linux (dist:jammy)"
        os: linux
        dist: jammy
        language: python
        python: 3.13
        env: python_version=3.13

  allow_failures:
    - python: 3.12
    - python: 3.13

cache:
  directories:
    - eggs
    - $HOME/.cache/pip
install:
  - pip install -U pip
  - pip install -e .[test]
  - pip install codecov
  - sleep 1
script:
  - make clean
  - make lint
  - black --check --verbose fhir/resources/
#  - pytest tests
  - pytest fhir/resources/STU3/tests
  - pytest -s --cov=fhir/resources/R4B/tests -s --tb=native -v --cov-report term-missing --cov-append fhir/resources/R4B/tests
  - pytest -s --cov=fhir/resources/tests -s --tb=native -v --cov-report term-missing --cov-append fhir/resources/tests
after_success:
  - codecov
